ALTER TABLE CLIENTE DROP CONSTRAINT c_cat;

ALTER TABLE CLIENTE ADD CONSTRAINT c_cat CHECK (CATEGORIA in ('VIP','PARTICULAR','EMPRESA'));

ALTER TABLE PRODUCTO ADD CONSTRAINT c_precio CHECK (Precio>0);

ALTER TABLE PRODUCTO ADD CONSTRAINT c_exist CHECK (Existencias >=10 and Existencias <=100);

ALTER TABLE PROVEEDOR ADD Edad Int DEFAULT '18';

ALTER TABLE COMPRA ADD CONSTRAINT fk_codigoPro FOREIGN KEY (Codigo_producto) REFERENCES PRODUCTO (Codigo_producto);

ALTER TABLE COMPRA ADD CONSTRAINT fk_codigoCli FOREIGN KEY (Codigo_Cliente) REFERENCES CLIENTE (Codigo_cliente);

ALTER TABLE SUMINISTRA ADD CONSTRAINT fk_codigoProv FOREIGN KEY (Codigo_proveedor) REFERENCES PROVEEDOR (Codigo_proveedor);

ALTER TABLE SUMINISTRA ADD CONSTRAINT fk_codigoProducto FOREIGN KEY (Codigo_producto) REFERENCES PRODUCTO (Codigo_producto);*/

/*BORRAMOS LAS TABLAS 

DROP TABLE COMPRA;
DROP TABLE SUMINISTRA;
DROP TABLE CLIENTE;
DROP TABLE PRODUCTO;
DROP TABLE PROVEEDOR;

*/