/* 1 */
SELECT NOMBRE FROM PRODUCTO;
/* 2*/
SELECT NOMBRE,PRECIO FROM PRODUCTO;
/*3*/
SELECT * FROM PRODUCTO;
/*4*/
SELECT NOMBRE,PRECIO, PRECIO * 0.82 FROM PRODUCTO;
/*5*/
SELECT NOMBRE AS "NOMBRE DE PRODUCTO", PRECIO AS "EUROS", PRECIO*0.82 AS "DOLARES" FROM PRODUCTO;
/*6*/
SELECT  UPPER (NOMBRE), precio  FROM PRODUCTO;
/*7*/
SELECT LOWER (NOMBRE), precio FROM PRODUCTO;
/*8*/
SELECT NOMBRE, UPPER(SUBSTR(NOMBRE,1,4)) FROM fabricante;

ALTER TABLE FABRICANTE rename column NOBMRE TO NOMBRE;
/*9*/
SELECT NOMBRE, ROUND(PRECIO) FROM PRODUCTO;
/*10*/
SELECT NOMBRE, TRUNC(PRECIO) FROM PRODUCTO;

SELECT SYSDATE FROM DUAL;

SELECT SYSDATE-3 FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'LUNES') FROM DUAL;

SELECT NEXT_DAY('18/12/2020','MARTES') FROM DUAL;

SELECT TO_DATE ('20012009','dd/mm/YY') FROM dual;

SELECT * FROM PRODUCTO WHERE PRECIO IS NULL;

SELECT PRECIO FROM PRODUCTO ORDER BY PRECIO ASC;

SELECT * FROM PRODUCTO ORDER BY PRECIO DESC, CODIGO_FABRICANTE ASC;
/*11*/
SELECT CODIGO_FABRICANTE FROM PRODUCTO;
/*12*/
SELECT DISTINCT(CODIGO_FABRICANTE) FROM PRODUCTO;
/*13*/
SELECT NOMBRE FROM FABRICANTE ORDER BY NOMBRE ASC;
/*14*/
SELECT NOMBRE FROM FABRICANTE ORDER BY NOMBRE DESC;
/*15*/
SELECT NOMBRE,PRECIO FROM PRODUCTO ORDER BY NOMBRE ASC, PRECIO DESC;
--16
SELECT NOMBRE,PRECIO FROM PRODUCTO ORDER BY PRECIO ASC;
SELECT codigo_fabricante from producto group by codigo_fabricante;
--17
SELECT NOMBRE,PRECIO FROM PRODUCTO ORDER BY PRECIO DESC;
--18
SELECT NOMBRE, CODIGO_FABRICANTE FROM PRODUCTO WHERE CODIGO_FABRICANTE=2;
--19
SELECT NOMBRE, Precio FROM PRODUCTO WHERE (precio<=120);
--20
SELECT NOMBRE, PRECIO FROM PRODUCTO WHERE (precio>=400);
--21
SELECT NOMBRE, PRECIO FROM PRODUCTO WHERE NOT(precio>=400);
--22
SELECT * FROM PRODUCTO WHERE (precio >=80 AND precio <=300);
SELECT * FROM PRODUCTO WHERE (PRECIO BETWEEN 80 AND 300);
--23
SELECT * FROM PRODUCTO WHERE (precio >=60 AND precio <=200);
--24
SELECT * FROM PRODUCTO WHERE (precio>400 AND codigo_fabricante=6);
--25
SELECT * FROM PRODUCTO WHERE (codigo_fabricante=1 OR CODIGO_FABRICANTE=3 OR CODIGO_FABRICANTE=5);
SELECT * FROM PRODUCTO WHERE CODIGO_FABRICANTE IN(1,3,5);
--26
SELECT NOMBRE, PRECIO*100 AS "CENTIMOS" FROM PRODUCTO;
--27
SELECT NOMBRE FROM FABRICANTE WHERE NOMBRE LIKE 'S%';
SELECT NOMBRE FROM FABRICANTE WHERE UPPER(NOMBRE) LIKE 'S%';
--28
SELECT NOMBRE FROM FABRICANTE WHERE NOMBRE LIKE '%e';
SELECT NOMBRE FROM FABRICANTE WHERE LOWER(NOMBRE) LIKE '%e';
--29
SELECT NOMBRE FROM FABRICANTE WHERE NOMBRE LIKE '%w%';
--30
SELECT NOMBRE FROM FABRICANTE WHERE NOMBRE LIKE '____';
SELECT NOMBRE FROM FABRICANTE WHERE LENGTH(NOMBRE)=4;
--31
SELECT NOMBRE FROM PRODUCTO WHERE NOMBRE LIKE '%Portátil%';
SELECT NOMBRE FROM PRODUCTO WHERE LOWER(NOMBRE) LIKE '%portátil%';
--32
SELECT NOMBRE FROM PRODUCTO WHERE NOMBRE LIKE '%Monitor%' AND PRECIO <215;
--33
SELECT NOMBRE, PRECIO FROM PRODUCTO WHERE PRECIO >= 180 ORDER BY PRECIO DESC, NOMBRE ASC;
--34
SELECT codigo_fabricante,count(codigo_fabricante) from producto group by codigo_fabricante;
--35
SELECT  CODIGO_FABRICANTE, SUM(PRECIO) FROM PRODUCTO GROUP BY CODIGO_FABRICANTE;
--35
SELECT COUNT(*) FROM PRODUCTO;
SELECT COUNT(DISTINCT (CODIGO_FABRICANTE)) FROM PRODUCTO;
SELECT CODIGO_FABRICANTE FROM PRODUCTO;