--CONSULTAS MULTITABLA

--1--

SELECT  PRODUCTO.NOMBRE, PRODUCTO.PRECIO,  FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE
WHERE PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO;

--2--

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE 
ORDER BY FABRICANTE.NOMBRE ASC;

--3--

SELECT PRODUCTO.CODIGO, PRODUCTO.NOMBRE, FABRICANTE.CODIGO , FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE
WHERE PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO;

--4--

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE 
WHERE PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO
ORDER BY PRECIO ASC ;

--5-- 

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE 
WHERE PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO
ORDER BY PRECIO DESC ;

--6--

SELECT PRODUCTO.*, FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE 
WHERE (PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO) AND (FABRICANTE.NOMBRE LIKE '%Lenovo%'); 

--7--
SELECT PRODUCTO.*, FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE 
WHERE (PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO) AND (FABRICANTE.NOMBRE LIKE '%Crucial%' and PRODUCTO.PRECIO>200);

--8--

SELECT PRODUCTO.*, FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE 
WHERE (PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO) AND (FABRICANTE.NOMBRE LIKE '%Asus%' or fabricante.nombre like '%Hewlett-Packard' or fabricante.nombre = 'Seagate');


--9--

SELECT PRODUCTO.*, FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE 
WHERE (PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO) AND (FABRICANTE.NOMBRE IN ('Asus' , 'Hewlett-Packard' ,'Seagate'));

--10--

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE
WHERE (PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO) AND (FABRICANTE.NOMBRE LIKE '%e');

--11--

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE
WHERE (PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO) AND (FABRICANTE.NOMBRE LIKE '%w%');

--12--

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO, FABRICANTE
WHERE (PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO) AND (PRODUCTO.PRECIO >= 180 ) ORDER BY PRODUCTO.PRECIO DESC, PRODUCTO.NOMBRE ASC;

--13

SELECT * FROM PRODUCTO ORDER BY CODIGO_FABRICANTE;
SELECT * FROM FABRICANTE;

SELECT PRODUCTO.CODIGO, FABRICANTE.CODIGO, FABRICANTE.NOMBRE FROM PRODUCTO LEFT JOIN FABRICANTE
ON PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO;

--14

SELECT PRODUCTO.CODIGO, PRODUCTO.NOMBRE, FABRICANTE.CODIGO, FABRICANTE.NOMBRE FROM PRODUCTO RIGHT JOIN FABRICANTE
ON PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO;

--15
SELECT FABRICANTE.CODIGO,FABRICANTE.NOMBRE,PRODUCTO.CODIGO FROM PRODUCTO,FABRICANTE
WHERE (PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO) AND PRODUCTO.NOMBRE IS NULL; --MAL

SELECT FABRICANTE.CODIGO,FABRICANTE.NOMBRE,PRODUCTO.CODIGO FROM PRODUCTO RIGHT JOIN FABRICANTE
ON PRODUCTO.CODIGO_FABRICANTE = FABRICANTE.CODIGO WHERE PRODUCTO.NOMBRE IS NULL;

