SAVEPOINT insertar;

INSERT INTO PRODUCTO VALUES(15,'Portatil',200,5);
INSERT INTO PRODUCTO VALUES(16,'Sobremesa',300,7);
INSERT INTO PRODUCTO VALUES(17,'Teclado',20,8);

SAVEPOINT BORRAR;

DELETE FROM PRODUCTO WHERE CODIGO_FABRICANTE=3;
DELETE FROM PRODUCTO WHERE NOMBRE LIKE '%Teclado%';

SAVEPOINT ACTUALIZAR;

UPDATE PRODUCTO SET NOMBRE='Actualizado';
UPDATE PRODUCTO SET PRECIO=200;


SELECT * FROM PRODUCTO;

ROLLBACK;

ROLLBACK TO SAVEPOINT insertar;

ROLLBACK TO SAVEPOINT BORRAR;

ROLLBACK TO SAVEPOINT ACTUALIZAR;