CREATE TABLE AUDITORIA_salario(
    nombre_tabla VARCHAR2(50),
    USUARIO VARCHAR2(50),
    FECHA DATE
    
);

CREATE OR REPLACE TRIGGER auditoria_salario
AFTER UPDATE  ON EMPLEADO FOR EACH ROW

BEGIN
    INSERT INTO AUDITORIA (nombre_tabla,usuario,fecha) VALUES ('Empleados', USER, SYSDATE);

END;

UPDATE EMPLEADO SET nombre = 'Juan' WHERE CODIGO_DEPARTAMENTO = 1;

SELECT * FROM EMPLEADO;

SELECT * FROM AUDITORIA;


CREATE OR REPLACE TRIGGER AUDITORIA
AFTER INSERT OR UPDATE OR DELETE ON DEPARTAMENTO FOR EACH ROW

BEGIN 
    IF INSERTING THEN
        INSERT INTO AUDITORIA (nombre_tabla,usuario,fecha) VALUES ('Insert en departamento', USER, SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO AUDITORIA (nombre_tabla,usuario,fecha) VALUES ('Actualización en departamento', USER, SYSDATE);
    ELSE 
        INSERT INTO AUDITORIA (nombre_tabla,usuario,fecha) VALUES ('Borrado en departamento', USER, SYSDATE);
END IF;

END;

INSERT INTO DEPARTAMENTO VALUES(10,'VIAJES',2000,1500);
INSERT INTO EMPLEADO VALUES(21,'76652179Q','Raul','Martinez','Fernandez',2,1500);
UPDATE DEPARTAMENTO SET PRESUPUESTO = 3000 WHERE CODIGO= 10;
DELETE FROM DEPARTAMENTO WHERE CODIGO= 10;

CREATE TABLE salarioNuevoViejo(
    SalarioOld NUMBER,
    SalarioNew NUMBER,
    Nombre_Tabla VARCHAR2(50),
    Usuario VARCHAR2(50),
    FECHA DATE
);

CREATE OR REPLACE TRIGGER SALARIO
AFTER UPDATE OF SALARIO ON EMPLEADO FOR EACH ROW

BEGIN
    INSERT INTO salarioNuevoViejo (SalarioOld,SalarioNew, Nombre_Tabla,Usuario, FECHA) VALUES (:old.salario,:new.salario,TABLE_NAME,USER, SYSDATE);
END;

CREATE OR REPLACE TRIGGER SALARIO
AFTER UPDATE OF SALARIO ON EMPLEADO  FOR EACH ROW WHEN (new.salario > old.salario)

BEGIN
    INSERT INTO salarioNuevoViejo (SalarioOld,SalarioNew, Nombre_Tabla,Usuario, FECHA) VALUES (:old.salario,:new.salario,'Empleados',USER, SYSDATE);
END;

UPDATE EMPLEADO SET SALARIO= 10000 WHERE CODIGO_DEPARTAMENTO= 2;

SELECT * FROM salarioNuevoViejo;