CREATE TABLE ESTADOS_CIVILES(

Codigo VARCHAR(1) PRIMARY KEY,
Nombre VARCHAR (20)


);

CREATE TABLE PERSONAS (

DNI VARCHAR (9) PRIMARY KEY,
Nombre VARCHAR(20),
Estado VARCHAR (1),
CONSTRAINT fk_codigo FOREIGN KEY (Estado) References Estados_civiles (codigo) ON DELETE CASCADE

);

INSERT INTO ESTADOS_CIVILES VALUES('S','Soltero');
INSERT INTO ESTADOS_CIVILES VALUES('C','Casado');
INSERT INTO ESTADOS_CIVILES VALUES('V','Viudo');

INSERT INTO PERSONAS VALUES('76652179X','Antonio','S');
INSERT INTO PERSONAS VALUES('1324132J','Juan','C');
INSERT INTO PERSONAS VALUES('1343244V','Ana','V');
INSERT INTO PERSONAS VALUES('2314325Z','Maria','C');

DELETE  FROM ESTADOS_CIVILES WHERE codigo = 'S';

SELECT * FROM PERSONAS;