CREATE TABLE PAISES (
CO_PAIS VARCHAR2(3) PRIMARY KEY,
DESCRIPCION VARCHAR2(20),
CONTINENTE VARCHAR2(20)
);

INSERT INTO PAISES VALUES ('ESP','ESPAÑA','EUROPA');
INSERT INTO PAISES VALUES ('FRA','FRANCIA','EUROPA');
INSERT INTO PAISES VALUES ('CN','CHINA','ASIA');
INSERT INTO PAISES VALUES ('JPN','JAPON','ASIA');
INSERT INTO PAISES VALUES ('ARG','ARGENTINA','AMERICA');
INSERT INTO PAISES VALUES ('BR','BRASIL','AMERICA');
INSERT INTO PAISES VALUES ('NG','NIGERIA','AFRICA');
INSERT INTO PAISES VALUES ('GH','GHANA','AFRICA');
INSERT INTO PAISES VALUES ('AUS','AUSTRALIA','OCEANIA');
INSERT INTO PAISES VALUES ('NZ','NUEVA ZELANDA','OCEANIA');

SELECT * FROM PAISES;

--CURSOR SIN PARAMETROS
DECLARE

CURSOR C_PAISES IS 

SELECT CO_PAIS,DESCRIPCION FROM PAISES;

V_REGISTRO C_PAISES%ROWTYPE;

BEGIN

OPEN C_PAISES;
    LOOP
        FETCH C_PAISES INTO V_REGISTRO;
        EXIT WHEN C_PAISES%NOTFOUND;
        dbms_output.put_line(V_REGISTRO.CO_PAIS || ' '|| V_REGISTRO.DESCRIPCION);
    END LOOP;
CLOSE C_PAISES;
END;

-- CURSOR CON PARAMETROS
DECLARE

CURSOR C_PAISES(v_continente paises.continente%type) IS 

SELECT CO_PAIS,DESCRIPCION FROM PAISES
WHERE continente=v_continente;
V_REGISTRO C_PAISES%ROWTYPE;

BEGIN

OPEN C_PAISES('ASIA');
    LOOP
        FETCH C_PAISES INTO V_REGISTRO;
        EXIT WHEN C_PAISES%NOTFOUND;
        dbms_output.put_line(V_REGISTRO.CO_PAIS || ' '|| V_REGISTRO.DESCRIPCION);
    END LOOP;
CLOSE C_PAISES;
END;