CREATE OR REPLACE PROCEDURE ACTUALIZAR ( v_nif IN empleado.nif%TYPE) is
v_codigo empleado.codigo%type;
v_codMax NUMBER;
BEGIN
SELECT codigo INTO v_codigo from empleado where v_nif= nif;
IF  v_codigo IS NOT NULL then 
UPDATE EMPLEADO SET SALARIO = 5000 WHERE v_codigo=codigo;
END IF;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
SELECT MAX(EMPLEADO.CODIGO)  INTO v_codMax FROM EMPLEADO; 
INSERT INTO EMPLEADO VALUES (v_codMax + 1,v_nif ,'','','',1,0);
END;


EXEC ACTUALIZAR ('70070080P');


SELECT * FROM EMPLEADO;

SELECT MAX(EMPLEADO.CODIGO) FROM EMPLEADO;
INSERT INTO EMPLEADO VALUES (SELECT MAX(EMPLEADO.CODIGO) FROM EMPLEADO + 1,NIF ,'','','',1 );

ALTER TABLE EMPLEADO ADD SALARIO NUMBER;

UPDATE EMPLEADO SET SALARIO=2000;